services:
    frontend:
        build:
        context: ./frontend #hledá Dockerfile ve složce frontend
        ports:
            - "80:80"
        depends_on:
            - backend

    backend:
        build:
        context: ./backend #hledá Dockerfile ve složce backend
        ports:
            - "8000:8000"
